apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-api
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: demo-api
  namespaceSelector:
    matchNames:
      - demo
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
